### ISSUE TITLE
Anonymized slug should be the same for staged and current

### ISSUE THREAD

**Issue by lojzatran** [commercetools/commercetools-node-variant-reassignment#58]
When anonymize, we should always take the slug from staged as a base and create an anonymized slug from it. 
We should not append staged and current separately as other tools updates only staged version of the product.

The problem that we have:
When we run sphere-product-import (SPI), we have a file with 2 products with same slug, but different variant:
```
P: "slug", v1
P: "slug", v2
```
We run SPI multiple times with the same product file and with product reassignment (PR) enabled.

1. run
SPI creates `P: "slug", v1` => `P: "id1", "slug", v1`
SPI throws an error on creating `P: "slug", v2` because of duplicated slug.
PR is not running.

CTP products: [`P: "id1", "slug", v1`]

2. run
PR gets a batch of `[P: "slug", v1; P: "slug", v2]`.
`P: "slug", v1` is not being processed by PR, because it's already existing.
`P: "slug", v2` being processed => it adds variant `v2` to `P1`, then it removes v1 from P1 and add an anonymized product `Px: "id2", "slug_anonym", v1`

CTP products: [`P: "id1", "slug", v2`, `Px: "id2", "slug_anonym", v1`]

SPI gets a batch of `[P: "slug", v1; P: "slug", v2]`. It will tries to update slug of `Px: "id2", "slug_anonym", v1` => 400 duplicate slug error.

CTP products: [`P: "id1", "slug", v2`, `Px: "id2", "slug_anonym", v1`]

3. run
PR gets a batch of `[P: "slug", v1; P: "slug", v2]`.
For `P: "slug", v1`:
- PR fetches both `P: "id1", "slug", v2` (match by slug), `Px: "id2", "slug_anonym", v1` (match by SKU).
- PR selects `Px: "id2", "slug_anonym", v1` as product to update (matches all SKUs)
- PR anonymize other products `P: "id1", "slug", v2` => `P: "id1", "slug_anonym", v2`

CTP products: [`P: "id1", "slug_anonym", v2`, `Px: "id2", "slug_anonym", v1`]

SPI gets batch of `[P: "slug", v1; P: "slug", v2]`.
For `P: "slug", v1`:
- it will update staged slug of `Px: "id2", "slug_anonym", v1` => [staged: `Px: "id2", "slug", v1`, current: `Px: "id2", "slug_anonym", v1`]
For `P: "slug", v2`:
It will tries to update slug of `P: "id1", "slug_anonym", v2` => 400 duplicate slug error.

CTP products: [`P: "id1", "slug_anonym", v2`, `Px: staged: { "id2", "slug", v1 }, current: { "id2", "slug_anonym", v1 }`]

4. run
PR gets a batch of `[P: "slug", v1; P: "slug", v2]`.
For `P: "slug", v1`:
- PR fetches `Px: staged: { "id2", "slug", v1 }, current: { "id2", "slug_anonym", v1 }`
- No actions are done for reassignment as variants matches and slug in staged is correct

For `P: "slug", v2`
- PR fetches `Px: staged: { "id2", "slug", v1 }, current: { "id2", "slug_anonym", v1 }` (by slug) and `P: "id1", "slug_anonym", v2` (by SKU)
- PR selects `P: "id1"` because it matches by all SKU
- **PR anonymizes `Px: staged: { "id2", "slug_anonym", v1 }, current: { "id2", "slug_anonym_anonym", v1 }`**

The problem is in the last action. Right now anonymization keeps appending random String to the end of the slug. So if we run the importer more times, the anonymized slug will be over 256 chars for current, which will result in 400 error from the platform.

**Comment by junajan** [comment]
😮 .. thx for perfect description
