### ISSUE TITLE
Create productManager

### ISSUE THREAD

**Issue by junajan** [commercetools/commercetools-node-variant-reassignment#7]
Create a class which will manage product operations like:
- deleteProduct
- createProduct
- getProductsBySku
- getProductById
- archiveProduct
- deleteVariantFromProduct
- isArchivedProduct

**Comment by butenkor** [comment]
why do we need archiveProduct?

**Comment by junajan** [comment]
maybe it is just wrongly named method - it should anonymize product (add _ctsd slug and change slugs and key)

**Comment by butenkor** [comment]
why not "anonymizeProductSlug"? :)

**Comment by junajan** [comment]
The method should anonymize whole product - update slugs, key, maybe also remove selected variants(?) and then save the anonymized product

**Comment by butenkor** [comment]
Is it specified in concept that key has to be anonymised also? 

The main point is that we have stick to naming convention of the concept. If anonymise is not suitable word than it has to be changed in concept also.

> maybe also remove selected variants

Why and what are selected variants?

**Comment by junajan** [comment]
You can for example anonymize product with three variants and remove one variant from it because it has to be reassigned to another product.

**Comment by junajan** [comment]
You can, for example, anonymize product with three variants and remove one variant from it because it has to be reassigned to another product.

**Comment by butenkor** [comment]
ok
